name: gamology_riverpod
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.1
  dio: ^5.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  rxdart: ^0.27.7
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  get_it: ^7.2.0
  flutter_widget_from_html_core: ^0.14.11
  intl: ^0.19.0
  webview_flutter: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - icons/